### ISSUE TITLE
st_folium map does not render in Chrome when in st.tabs

### ISSUE THREAD

**Issue by matthalstead** [randyzwitch/streamlit-folium#128] opened 2023-06-18 21:36 UTC
It seems that in Chrome, if st_folium is used within the 2 or higher tab in an st.tabs, then it won't render the map. I don't see this issue on Safari. There are no errors in browser console. This may be an issue with st.tabs, but starting here first since it's only st_folium objects not rendering.

```
    import folium
    from streamlit_folium import st_folium
    import streamlit as st
    
    
    st.title("Location stuff")
    tab1, tab2 = st.tabs(["tab1", "tab2"])
    
    with tab1:
        st.text('tab1')
    
    with tab2:
        center = [-36.85605386574607, 174.75310922743114]
        m = folium.Map(location=center, zoom_start=10)
        st_folium(m, width=725)
```

Chrome : Version 114.0.5735.133 (Official Build) (arm64)
Streamlit: 1.23.1
Streamlit-folium: 0.12.0
OS : Mac OS 13.4 (22F66) - Ventura
Python: 3.10.9

**Comment by randyzwitch** [comment] 2023-06-21 13:32
@kmcgrady not sure if this is something y'all are interested in troubleshooting from the `st.tabs` side. Not expecting a PR here, I'm just lazily assuming this is an edge case in `st.tabs`

**Comment by matthalstead** [comment] 2023-08-30 20:51
Do I need to submit a bug report in st.tabs?

**Comment by randyzwitch** [comment] 2023-08-30 22:20
I would say yes, submit a ticket with Streamlit.

**Comment by matthalstead** [comment] 2023-09-20 00:14
I have submitted a ticket here : https://github.com/streamlit/streamlit/issues/7376

In an additional comment I also show where the issue may lie and a workaround I can use in my own custom components. I am not sure if this is the right solution, but streamlit-folium users may want to know about it.

**Comment by randyzwitch** [comment] 2023-12-07 13:56
Closing this, since there is an open ticket at Streamlit and they have confirmed its their behavior to be fixed

**Closed by randyzwitch** 2023-12-07 13:56 UTC
Labels: upstream
