### ISSUE TITLE
Draw support - finish option doesn't work

### ISSUE THREAD

**Issue by OmkarjoshiEll0254** [randyzwitch/streamlit-folium#203] opened 2024-07-12 13:27 UTC
I am trying to add draw line option and picking the coordinates. But finish option is not working once I draw a line. Attached screenshot below:
![image](https://github.com/user-attachments/assets/0f70cd20-71f3-4cf8-8ed5-1bebb753794c)

**Comment by hansthen** [comment] 2024-09-15 18:47
Is this the same issue as https://github.com/randyzwitch/streamlit-folium/issues/161? There are more reports of the Draw plugin not working everywhere. Weirdly enough, I cannot reproduce this issue locally.

@OmkarjoshiEll0254 could you add the versions of `folium` and `streamlit-folium` and `streamlit` you are using? It would also be helpful to know what browser version you are using.

**Comment by OmkarjoshiEll0254** [comment] 2024-09-16 12:27
@hansthen sorry. I am no longer using streamlit. But just to confirm, I was using 
streamlit : 1.32.1
streamlit_folium : 0.21.0

Thanks

**Comment by hansthen** [comment] 2024-09-16 16:29
@randyzwitch I think I found the cause of this issue. However, there seem to be some problems with the build pipeline, which are not related to my PR. Could you have a look to see what's the issue with the build pipeline?

**Comment by blackary** [comment] 2024-09-16 17:51
Closed by #211

**Closed by blackary** 2024-09-16 17:51 UTC
Labels: bug, draw
